usage: |
  Adds the "page_size" and "offset" query string parameters that allow clients to regulate how many
  items to return for the request.
queryParameters:
  page_size:
    description: The number of items to return
    type: integer
  offset:
    description: The item at which to begin the response
    type: integer

